#!/bin/sh

echo "==================== commitlint::start ========================"
echo "🔎 Running commitlint"
npx --no -- commitlint --edit "$1"
echo "✅ Commitlint completed."
echo "==================== commitlint::end ========================"